keys:
  # nix run nixpkgs#ssh-to-age -- -i ~/.ssh/id_ed25519.pub
  - &dguibert 3198EB02EB0EEC85FE5BF6AC4E6EE5C219FDD513
  - &dguibert_titan_age age1gthhn69gtgn8gsvv58xqu9vxfnczl68kktm64638xfv5j3qm4grqeuw0h4
  - &dguibert_t580_age age1zpv9vp6rkcttpg8yk5qk8yjh4kxh6pj9d3uvzfekglth6mfc0drqekue6r
  - &titan_age age1d2np6ey39hl6ju270v4gvxta2m0ckvp9jxa53398ynsaf5w4v3tswd5w6r
  - &rpi41_age age1ncf2lnt6kv4x3d247u06gh0p4u7qs2xpr8yzmxk7c03rn6pwp4fsy9928j
  - &rpi31_age age1q7tetslupq5nqevldsx2pnc54lvxrwkggynqncvdzhudv8p6zamqvts9qq
  - &t580_age age14sj2anmfrckcuujl2ea0udsgxcunr2wncvk05q32p5kj8fljzpvq3fuez5
creation_rules:
  # dguibert
  - path_regex: modules/clan/home-manager/roles/dguibert/[^/]+-sec\.nix$
    key_groups:
      - pgp:
          - *dguibert
  # dguibert
  # titan
  - path_regex: hosts/titan/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *titan_age
  # dguibert
  # rpi41
  - path_regex: hosts/rpi41/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *rpi41_age
  # dguibert
  # rpi31
  - path_regex: hosts/rpi31/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *rpi31_age
  # dguibert
  # t580
  - path_regex: hosts/t580/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *t580_age
  # dguibert
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *rpi31_age
          - *rpi41_age
          - *t580_age
          - *titan_age
  - path_regex: modules/home-manager/dguibert/[^/]+-sec\.nix$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *rpi31_age
          - *rpi41_age
          - *t580_age
          - *titan_age
  - path_regex: modules/clan/home-manager/roles/dguibert/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *dguibert_titan_age
          - *dguibert_t580_age
  - path_regex: sops/secrets/id_buildfarm/secret
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *dguibert_titan_age
          - *rpi41_age
          - *t580_age
          - *titan_age
